# Generated by Django 4.2.3 on 2023-08-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameWeb', '0002_alter_customer_phone_number_alter_game_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GameWeb.order'),
        ),
    ]
